'use strict'

import SERVER_CONFIG from './SERVER_CONFIG'
import EXPS_CONFIG from './EXPS_CONFIG'
import MICROSERVICES_ENDPOINTS from './MICROSERVICES_ENDPOINTS'
import DIR_CONFIG from './DIR_CONFIG'

export {
  SERVER_CONFIG,
  EXPS_CONFIG,
  MICROSERVICES_ENDPOINTS,
  DIR_CONFIG,
}
